blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community Forum
    url: https://community.home-assistant.io/
    about: Get help from the Home Assistant community
  - name: Tibber Support
    url: https://support.tibber.com/
    about: For issues with your Tibber account or service
  - name: HACS Support
    url: https://github.com/hacs/integration
    about: For HACS installation or repository issues