name: Feature Request
description: Suggest a new feature for the Tibber Unofficial integration
title: "[Feature]: "
labels: [enhancement, needs-triage]
assignees:
  - senaxx

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

        **Note**: This integration uses undocumented Tibber APIs, so new features depend on what data is available.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Explain how this feature would be useful
      placeholder: |
        - Who would benefit from this feature?
        - What problem does it solve?
        - How would you use it?
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: If you have ideas for how this could be implemented, describe them
      placeholder: How do you think this should work?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there any alternative solutions or workarounds you've considered?
      placeholder: What other approaches could achieve similar results?

  - type: checkboxes
    id: tibber_availability
    attributes:
      label: Tibber Data Availability
      description: Does this feature require data from Tibber?
      options:
        - label: This feature would require new data from Tibber's API
          required: false
        - label: This data is visible in the official Tibber app
          required: false
        - label: This is a UI/UX improvement that doesn't need new API data
          required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to test this feature when available
          required: false
        - label: I could help with implementation (code)
          required: false
        - label: I could help with testing and feedback
          required: false
        - label: I could help with documentation
          required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Screenshots, mockups, examples from other integrations, etc.